### ISSUE TITLE
Recorded PPG Signals looks clipped

### ISSUE THREAD

**Issue by niv22** [Protocentral/protocentral_max86150_ecg_ppg#4]
Hello,
We were testing the PPG signal of the sensor. We were able to see signal correctly in the Openview GUI. But the saved signal appears clipped or quantized as shown in the image below. (The plot is generated in python using matplotlib) 
![Capture (2)](https://user-images.githubusercontent.com/29995820/109756640-51482100-7c0e-11eb-85f6-acee1aa188df.JPG)

The PPG data looks like this: 
...
 231.0,
 231.0,
 231.0,
 226.0,
 226.0,
 226.0,
 226.0,
 228.0,
 228.0,
 228.0,
 228.0,
 228.0,
 228.0,
 228.0,
 228.0,
...
It can be observed that each value is being repeated four times and there is significant difference between the non-repeating values which does not result in a smooth signal. Is there some processing that we need to do once we record the signal in-order to get the proper waveform?

**Comment by diegotorpoco** [comment]
Hello, could you solve this issue? I have a similar graph for the ECG signal, as if it was a discrete signal.

**Comment by joicetm** [comment]
Hi,

It looks like oversampling, have you made any changes to the library ?
can you please share your code and some images of your output ?

**Comment by diegotorpoco** [comment]
Hi, 

I have fixed the issue by disconnecting the laptop's battery. It seems that it was causing a noise. Now I have a better EKG signal compared to before . This has been filtered already. 

![image](https://user-images.githubusercontent.com/64674242/119603237-6c13d700-bdb2-11eb-87ff-af8b9c766276.png)

**Comment by joicetm** [comment]
Great, we are glad that you were able to fix the issue.
AC noise will cause distortion to the signal.
